using System;
using UnityEngine;
using UnityEngine.Assertions;

namespace FS.Patterns
{
    public static class ApplicationState
    {
        public static bool IsQuitting { get; private set; }

        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]
        private static void Init()
        {
            IsQuitting = false;
            
            Application.quitting -= OnApplicationQuit;
            Application.quitting += OnApplicationQuit;
        }
        
        private static void OnApplicationQuit() => IsQuitting = true;
    }
    
    public abstract class MonoSingleton<T> : MonoBehaviour where T : Component
    {
        private static T _instance;

        public static bool HasInstance => _instance != null;
        public static T TryGetInstance => _instance;

        public static T Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = FindAnyObjectByType<T>();
                    if (_instance == null && !ApplicationState.IsQuitting) // Do not create gameobjects when quitting
                    {
                        var go = new GameObject(typeof(T).Name + "_Singleton_AutoGenerated");
                        _instance = go.AddComponent<T>();
                    }
                }

                return _instance;
            }
        }
        
        /// <summary>
        /// Make sure to call base.Awake() in override as it initializes the singleton
        /// </summary>
        protected virtual void Awake()
        {
            InitializeSingleton();            
        }

        protected virtual void InitializeSingleton()
        {
            if (!Application.isPlaying) return;
            _instance = this as T;
        }
    }
    
    /// <summary>
    /// Persistent Singleton, prevents newer objects of this type from being created. Marked for DontDestroyOnLoad
    /// </summary>
    public abstract class PersistentSingleton<T> : MonoBehaviour where T : Component
    {
        private static T _instance;

        public static bool HasInstance => _instance != null;
        public static T TryGetInstance => _instance;

        public static T Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = FindAnyObjectByType<T>();
                    if (_instance == null && !ApplicationState.IsQuitting) // Do not create gameobjects when quitting
                    {
                        Debug.Log($"Singleton Created For: {typeof(T).Name}");
                        var go = new GameObject(typeof(T).Name + "_Singleton_AutoGenerated");
                        _instance = go.AddComponent<T>();
                    }
                }

                return _instance;
            }
        }
        
        /// <summary>
        /// Make sure to call base.Awake() in override as it initializes the singleton
        /// </summary>
        protected virtual void Awake()
        {
            Debug.Log("Singleton Awake!");
            InitializeSingleton();            
        }

        protected virtual void InitializeSingleton()
        {
            if (!Application.isPlaying) return;
            
            // Dont destroy on load only works if the gameobject is a root gameobject, so unparent if it isnt
            if (transform.parent != null)
            {
                //Assert.IsNull(transform.parent, $"Transform parent of persistent");
                throw new NotSupportedException(
                    $"Transform parent of persistent singleton {gameObject.name} was not null!");
                transform.SetParent(null);
            }

            if (_instance == null)
            {
                _instance = this as T;
                DontDestroyOnLoad(gameObject);
            }
            else if (_instance != this)
            {
                throw new NotSupportedException($"Multiple instances of singleton {typeof(T)} detected!");
                Destroy(gameObject);
            }
        }
    }
    
    /// <summary>
    /// Persistent Regulator Singleton, will destroy any other older components of the same type it find on awake.
    /// E.g, newer instances will replace older instances
    ///
    /// Useful for automatically swapping out core systems like an AudioSystem for UI vs Game when swapping between the two
    /// </summary>
    public abstract class RegulatorSingleton<T> : MonoBehaviour where T : Component
    {
        private static T _instance;

        public static bool HasInstance => _instance != null;

        public float InitializationTime { get; private set; }
        
        public static T Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = FindAnyObjectByType<T>();
                    if (_instance == null && !ApplicationState.IsQuitting) // Do not create gameobjects when quitting
                    {
                        var go = new GameObject(typeof(T).Name + "_Singleton_AutoGenerated");
                        go.hideFlags = HideFlags.HideAndDontSave;
                        _instance = go.AddComponent<T>();
                    }
                }

                return _instance;
            }
        }
        
        /// <summary>
        /// Make sure to call base.Awake() in override as it initializes the singleton
        /// </summary>
        protected virtual void Awake()
        {
            InitializeSingleton();            
        }

        protected virtual void InitializeSingleton()
        {
            if (!Application.isPlaying) return;

            InitializationTime = Time.time;
            DontDestroyOnLoad(gameObject);

            // Find any other instances of this type and destroy them
            var oldInstances = FindObjectsByType<T>(FindObjectsSortMode.None);
            foreach (var old in oldInstances)
            {
                if (old.GetComponent<RegulatorSingleton<T>>().InitializationTime < InitializationTime)
                {
                    Destroy(old.gameObject);
                }
            }
            
            if (_instance == null)
            {
                _instance = this as T;
            }
        }
    }
}