using UnityEngine;
using UnityEditor;
using System.IO;
using UnityEngine.Rendering;

namespace FS.Editor
{
    /// <summary>
    /// Simple generic tool to create a texture from a material by just rendering it out and saving it
    /// </summary>
    public class MaterialTextureBaker : EditorWindow
    {
        private Material targetMaterial;
        private Shader targetShader;
        private int selectedResolutionIndex = 2; // Default to 512x512
        private readonly int[] resolutions = { 64, 128, 256, 512, 1024, 2048, 4096 };
        private string[] resolutionStrings;
        
        private RenderTexture renderTexture;
        private Texture2D previewTexture;
        private bool showPreview = false;
        private Source source = Source.Material;
        
        private bool CanGeneratePreview => (source == Source.Shader && targetShader != null) || (source == Source.Material && targetMaterial != null);

        private string AutogeneratedName => (source == Source.Material
            ? (targetMaterial ? targetMaterial.name : "NULL")
            : (targetShader ? targetShader.name : "NULL")); 

        private enum Source
        {
            Material, Shader
        }
        
        [MenuItem("Tools/Material Texture Baker")]
        public static void ShowWindow()
        {
            var window = GetWindow<MaterialTextureBaker>("Material Texture Baker");
            window.minSize = new Vector2(400, 525);
        }
        
        private void OnEnable()
        {
            // Create resolution strings for dropdown
            resolutionStrings = new string[resolutions.Length];
            for (int i = 0; i < resolutions.Length; i++)
            {
                resolutionStrings[i] = $"{resolutions[i]} x {resolutions[i]}";
            }
        }
        
        private void OnGUI()
        {
            EditorGUILayout.Space(10);
            
            // Title
            EditorGUILayout.LabelField("Material to Texture Baker", EditorStyles.boldLabel);
            EditorGUILayout.HelpBox("Bake a material/shader into a PNG texture.", MessageType.Info);
            
            EditorGUILayout.Space(10);
            
            source = (Source)EditorGUILayout.EnumPopup("", source);
            
            // Material Or Shader Selection
            EditorGUILayout.BeginVertical(EditorStyles.helpBox);
            
            EditorGUI.BeginChangeCheck();

            if (source == Source.Material)
            {
                EditorGUILayout.LabelField("Source Material", EditorStyles.boldLabel);
                targetMaterial = EditorGUILayout.ObjectField("Material", targetMaterial, typeof(Material), false) as Material;
            }
            else if (source == Source.Shader)
            {
                EditorGUILayout.LabelField("Source Shader Graph", EditorStyles.boldLabel);
                targetShader = EditorGUILayout.ObjectField("Shader", targetShader, typeof(Shader), false) as Shader;
            }

            if (EditorGUI.EndChangeCheck())
            {
                // Clear preview when material or shader changes
                showPreview = false;
                CleanupPreviewTextures();
            }
            
            EditorGUILayout.EndVertical();
            
            EditorGUILayout.Space(10);
            
            // Resolution Selection
            EditorGUILayout.BeginVertical(EditorStyles.helpBox);
            EditorGUILayout.LabelField("Output Settings", EditorStyles.boldLabel);
            selectedResolutionIndex = EditorGUILayout.Popup("Resolution", selectedResolutionIndex, resolutionStrings);
            EditorGUILayout.EndVertical();
            
            EditorGUILayout.Space(10);
            
            // Action Buttons
            EditorGUILayout.BeginHorizontal();
            
            GUI.enabled = CanGeneratePreview;
            
            if (GUILayout.Button("Preview", GUILayout.Height(30)))
            {
                GeneratePreview();
            }
            
            if (GUILayout.Button("Bake and Save", GUILayout.Height(30)))
            {
                BakeAndSaveTexture();
            }
            
            GUI.enabled = true;
            
            EditorGUILayout.EndHorizontal();
            
            EditorGUILayout.Space(10);
            
            // Preview Display
            if (showPreview && previewTexture != null)
            {
                EditorGUILayout.BeginVertical(EditorStyles.helpBox);
                EditorGUILayout.LabelField("Preview", EditorStyles.boldLabel);
                
                // Calculate preview size to fit in window
                float maxPreviewSize = position.width - 40;
                float previewSize = Mathf.Min(maxPreviewSize, 256);
                
                GUILayout.BeginHorizontal();
                GUILayout.FlexibleSpace();

                Rect previewRect = GUILayoutUtility.GetRect(previewSize, previewSize);
                EditorGUI.DrawPreviewTexture(previewRect, renderTexture);
                
                GUILayout.FlexibleSpace();
                GUILayout.EndHorizontal();
                
                EditorGUILayout.LabelField($"Size: {previewTexture.width}x{previewTexture.height}", EditorStyles.centeredGreyMiniLabel);
                
                EditorGUILayout.EndVertical();
            }
        }
        
        private void GeneratePreview()
        {
            if (!CanGeneratePreview)
            {
                EditorUtility.DisplayDialog("Error", "Please assign a material first.", "OK");
                return;
            }
            
            int resolution = resolutions[selectedResolutionIndex];
            var bakedTexture = BakeMaterialToTexture(resolution);
            
            if (bakedTexture != null)
            {
                CleanupPreviewTextures();
                previewTexture = bakedTexture;
                showPreview = true;
                Repaint();
            }
        }
        
        private void BakeAndSaveTexture()
        {
            if (!CanGeneratePreview)
            {
                EditorUtility.DisplayDialog("Error", "Please assign a material first.", "OK");
                return;
            }
            
            int resolution = resolutions[selectedResolutionIndex];
            
            // Bake the texture
            var bakedTexture = BakeMaterialToTexture(resolution);
            
            if (bakedTexture == null)
            {
                EditorUtility.DisplayDialog("Error", "Failed to bake texture.", "OK");
                return;
            }
            
            // Save dialog
            string defaultName = AutogeneratedName + "_Baked";
            string path = EditorUtility.SaveFilePanel(
                "Save Baked Texture",
                "Assets",
                defaultName,
                "png"
            );
            
            if (string.IsNullOrEmpty(path))
            {
                DestroyImmediate(bakedTexture);
                return;
            }
            
            // Convert to PNG and save
            byte[] pngData = bakedTexture.EncodeToPNG();
            File.WriteAllBytes(path, pngData);
            
            // If saved in project, import it
            if (path.StartsWith(Application.dataPath))
            {
                AssetDatabase.Refresh();
                string relativePath = "Assets" + path.Substring(Application.dataPath.Length);
                
                // Select the newly created texture
                var savedTexture = AssetDatabase.LoadAssetAtPath<Texture2D>(relativePath);
                if (savedTexture != null)
                {
                    Selection.activeObject = savedTexture;
                    EditorGUIUtility.PingObject(savedTexture);
                }
            }
            
            // Update preview
            CleanupPreviewTextures();
            previewTexture = bakedTexture;
            showPreview = true;
            Repaint();
        }
        
        private Texture2D BakeMaterialToTexture(int resolution)
        {
            var renderMaterial = source == Source.Material
                ? targetMaterial
                : new Material(targetShader) { hideFlags = HideFlags.HideAndDontSave };
            
            // Update RT size if needed
            if (renderTexture != null)
            {
                if (renderTexture.width != resolution || renderTexture.height != resolution)
                {
                    RenderTexture.ReleaseTemporary(renderTexture);
                    renderTexture = null;
                }
            }
            
            // Create a temporary render texture & render our material to it
            if (renderTexture == null)
                renderTexture = RenderTexture.GetTemporary(resolution, resolution);
            
            Graphics.Blit(null, renderTexture, renderMaterial, 0);
            Texture2D result = new Texture2D(resolution, resolution)
            {
                hideFlags = HideFlags.HideAndDontSave
            };
            
            // Transfer to a texture2D
            RenderTexture.active = renderTexture;
            result.ReadPixels(new Rect(0, 0, resolution, resolution), 0, 0);
            RenderTexture.active = null;
            
            if (source == Source.Shader)
                Object.DestroyImmediate(renderMaterial);
            
            return result;
        }
        
        private void CleanupPreviewTextures()
        {
            if (previewTexture != null)
            {
                DestroyImmediate(previewTexture);
                previewTexture = null;
            }
        }
        
        private void OnDisable()
        {
            if (renderTexture != null)
            {
                RenderTexture.ReleaseTemporary(renderTexture);
                renderTexture = null;
            }
            CleanupPreviewTextures();
        }
    }
}